### ISSUE TITLE
web2py.py fails to run locally

### ISSUE THREAD

**Issue by ghost** [prelegalwonder/openshift_web2py#1]
anytime I try `python2.7 web2py.py` I get

```
Traceback (most recent call last):
  File "web2py.py", line 16, in <module>
  import gluon.widget
  ImportError: No module named gluon.widget
```

**Comment by prelegalwonder** [comment]
Yeah, this is because for openshift we moved gluon into the libs dir. There are a few approaches you can take. 
1. extend your sys.path to include the libs/gluon dir for your local runtime (check the PYTHONPATH environment variable usage)
2. run a separate vanilla web2py instance and use my openshift deployer from the admin page in my fork of the web2py repo. Hopefully Massimo will accept my pull request and pull this feature back in to trunk.

Let me know if you need more specifics

**Comment by ghost** [comment]
That makes sense. I'm already using a version of symlinking with another standard install of web2py. I wanted to run the one included as I thought it would help me debug the other issue that you solved for me. Thanks again.
