### ISSUE TITLE
Cloud Storage Service

### ISSUE THREAD

**Issue by ashrafmansour** [prelegalwonder/openshift_web2py#11]
Hi,

which cloud storage service is accessible from openshift-deployed web2py app?

s3 , dropbox , google drive , ...

My main purpose is to store photos.

Regards,

Ashraf

**Comment by prelegalwonder** [comment]
I haven't tried to setup any of these as the storage provided by the openshift account is enough for my purposes. However they all should be accessible from openshift in that network access isn't restricted. 

If you want a filesystem mount instead of using things like boto (http://boto.s3.amazonaws.com/s3_tut.html) then you'll probably need to look into FUSE tutorials. 

Unless you really need filesystem access I'd look at just using the provided web service points of entry for the different services and what api's leverage those.

**Comment by ashrafmansour** [comment]
Thank you Andrew...

How do you monitor the storage used in openshift?

**Comment by ashrafmansour** [comment]
is it newrelic?

**Comment by prelegalwonder** [comment]
no, newrelic is for performance monitoring (requests/sec, how long a method takes to execute, slow sql performance)

For disk stuff see:

https://openshift.redhat.com/community/faq/how-much-disk-space-do-i-get-with-openshift

**Comment by ashrafmansour** [comment]
Thanks...
