### ISSUE TITLE
web2py 2.2.1

### ISSUE THREAD

**Issue by ashrafmansour** [prelegalwonder/openshift_web2py#12]
Hi,

Currently, openshift_web2py is based on 2.0.9. So, openshift applications are based currently on 2.0.9.

Eventually, openshift_web2py will be based on 2.2.1.

How will the applications be upgraded?

Regards,

Ashraf

**Comment by prelegalwonder** [comment]
Sorry, I've been pre-occupied with other things. If you're using the in-cloud admin vs the deploy to openshift, using the admin to upgrade may work. I haven't tried though. 

Otherwise you can just overwrite the web2py dir with the new version and copy gluon over to the libs dir and commit / push. 

I'll try to get it officially updated soon.

**Comment by SamuelMarks** [comment]
Thanks, looking forward to the officially updated version.

**Comment by ashrafmansour** [comment]
After using the admin to upgrade to 2.2.1, it says that it has been upgraded and needs to be restarted. After restarting the version is 2.0.9.

there is a warning that it is experimental.

**Comment by ashrafmansour** [comment]
I tried the way of copy gluon to libs and commit/push, the version is still 2.0.9.

I have no clue.

**Comment by prelegalwonder** [comment]
I've updated to 2.2.1 but haven't experimented much. Please give it a test and report any issues. As I get time I'm going to see if I can automate upgrades with Jenkins
