### ISSUE TITLE
Application file error?

### ISSUE THREAD

**Issue by lzac** [prelegalwonder/openshift_web2py#13]
Hi, I' ve followed your great guide to set up web2py skeleton on github but I kept receiving 500 internal error when accessing the app from browser.

Looking at the server error log (rhc tail -a myappname -l mymail -p mypwd) I got this:

[Tue Nov 13 05:46:53 2012] [error] [client 127.8.12.1]     WEB2PY_LOG = os.path.join(os.environ['OPENSHIFT_LOG_DIR'],'web2py.log')
[Tue Nov 13 05:46:53 2012] [error] [client 127.8.12.1]   File "/usr/lib64/python2.6/UserDict.py", line 22, in **getitem**
[Tue Nov 13 05:46:53 2012] [error] [client 127.8.12.1]     raise KeyError(key)
[Tue Nov 13 05:46:53 2012] [error] [client 127.8.12.1] KeyError: 'OPENSHIFT_LOG_DIR'

OPENSHIFT_LOG_DIR was not found in os so I just changed it to OPENSHIFT_REPO_DIR and everything starts working.

Is it my fault or openshift has changed from your last push? 

Thanks and hands-clapping for your great work!

**Comment by prelegalwonder** [comment]
I haven't tried since the last few Openshift updates. It's possible they changed / removed the environment variable for openshift_log_dir. If you ssh into your gear and type env  you should be able to see all variables. If I get some time I'll try and update the repo to the latest release and take a look at whats changed with the Openshift environment. Thanks for reporting this.

**Comment by lzac** [comment]
Of course that was the problem, that variable is no more in the gear.
Looking at actually used env variables the most suitable one to be used seems be OPENSHIFT_PYTHON_LOG_DIR.
Don't think the repo needs other changes, everything works really fine!

**Comment by prelegalwonder** [comment]
Glad to hear it :)
