### ISSUE TITLE
Script installing an old web2py version?

### ISSUE THREAD

**Issue by paulo242** [prelegalwonder/openshift_web2py#17]
Please correct me if I´m wrong, but seems like the script is not installing the lastest version fo web2py. I´m using a call like /<myapp>/<controller>/get.json and getting an error like: invalid view. In newer versions of web2py when you as for a .json it gets you that.

**Comment by prelegalwonder** [comment]
Sorry, I haven't had much time to maintain this and keep it up to date. I setup a Jenkins job to pull in updates to web2py master and rebuild this template but it appears the job is currently broken. I'll take a look at it this weekend.

**Comment by paulo242** [comment]
Please man, do not appologize. You are doing a great job on that. Please let me know if I can help. I don´t have much knowlegment about it, but guess I can help testing. Thanks a lot.

**Comment by prelegalwonder** [comment]
This should be fixed. I had taken a merge request that broke the pull process from Massimo's upstream repo. I've reverted it and master of this project should now be master of web2py. Give it a shot when you have a chance and let me know.

**Comment by liuyigh** [comment]
@prelegalwonder Hi, Thanks a lot for providing this. It seems it's outdated again (2.6 instead of 2.8 current).

**Comment by prelegalwonder** [comment]
I apologize, I no longer have the time to maintain this repo. The steps to update are relatively simple to update. You checkout the repo, blow away wsgi/web2py and unzip the new src distro in there. 

If you find this is something you need often and aren't comfortable doing a manual upgrade, I'd petition Massimo to get this added to the projects Travis.ci integration tests.

**Comment by liuyigh** [comment]
@prelegalwonder please do not apologize. You web2py people are inconceivably nice! Web2py is so easy to learn and use. I have a small web2py app deployed on OpenShift. I developed everything in just a few days of spare time. Btw, I only had some basic python and html skills and ZERO wsgi experience before using Web2Py. So I really appreciate you providing this.

Right now, Openshift installs a Django framework to it's default python cartridge, but no official Web2Py support. Although I don't know how influential Openshift is in the PaaS market, I feel web2py is losing market share to Django without some kind of support on OpenShift, especially when you provide a "Deploy to OpenShift" function in your admin.

I am not sure if you are in the web2py team. If possible, please convey my regards and this message to Massimo.

I am new to git version control system. I will try manual update when I learn more about it.

**Comment by liuyigh** [comment]
Sorry for keep asking you. I tried to replace the wsgi/web2py folder with newest source zip. However, I've got this error with git push:

remote: ln: creating symbolic link `/var/lib/openshift/52af83725973ca14640000ab/app-root/runtime/repo//wsgi/web2py/gluon': File exists
remote: An error occurred executing 'gear postreceive' (exit code: 1)
remote: Error message: Failed to execute action hook 'build' for 52af83725973ca14640000ab application py

I tried to install a entire new openshift application. Same error.

**Comment by prelegalwonder** [comment]
You need to mv the contents of web2py/gluon to /libs/ overwriting the old gluon then link to that dir (ln -s libs/gluon wsgi/web2py/gluon ). Then make sure you do git add . from the / of the repo and then commit and push. 

Sorry it's wonky because I was trying to follow the openshift gear principles but removing gluon from the web2py dir causes issues so I account for that in the wsgi/application file by adding it to the PYTHON_PATH. 

You could probably completely restructure the template to just leave gluon in web2py and just use libs/for other 3rd party libs that can't be defined with the setup.py's "install_requires"

**Comment by liuyigh** [comment]
@prelegalwonder Thanks for the solution. I just need to mv the web2py/gluon to libs/ and remove the old one. No need to ln -s, since your script is trying to do it. If I ln -s, I will get the same error.

Now running py 2.7.5 + web2py 2.8.2 woo-hoo! Maybe we can update your github readme.md page :)

Update: I just edited the wiki page to show how to upgrade.

**Comment by prelegalwonder** [comment]
Awesome, thank you! Glad to hear everything is working :)

**Comment by prelegalwonder** [comment]
Closing this, thanks for the wiki contribution!
